# Generated by Django 3.1.1 on 2021-06-02 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20200921_2334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=70),
        ),
        migrations.DeleteModel(
            name='Trending',
        ),
    ]
